#配置JDBC连接信息
spring:
  #配置JDBC连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rsmsp_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    #配置使用数据库连接池为druid
    type: com.alibaba.druid.pool.DruidDataSource
    #配置druid连接池信息
    druid:
      #最大连接数
      min-idle: 3
      #最小连接数
      max-active: 15
      #初始化数量
      initial-size: 5
      #最小存活时间
      min-evictable-idle-time-millis: 30000
      #最大存活时间
      max-evictable-idle-time-millis: 60000
      #配置druid监控中心信息
      stat-view-servlet:
        #开启监控中心功能
        enabled: true
        #设置监控中心登录用户名和密码
        login-username: druid
        login-password: 123456
        #监控中心登录地址
        url-pattern: /druid
      #配置监控中心网页管理信息
      web-stat-filter:
        #开启前端管理界面
        enabled: true
          #配置系统监控系统所需要的URL请求格式
        url-pattern: /*
          #配置忽略某些请求监控
        exclusions: /druid/*, *.js, *.gif, *.jpg, *.png, *.css, *.ico
#配置Mybatis信息
mybatis:
  mapper-locations: classpath:/mapper/*/*.Mapper.xml
  type-aliases-package: cn.kang.rsmsp.*.pojo.entity
